# Generated by Django 4.2 on 2023-05-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.IntegerField(null=True)),
                ('feels_like', models.IntegerField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('type', models.TextField(null=True)),
                ('icon', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.register')),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
