# Generated by Django 4.2 on 2023-05-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_w'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='w',
            new_name='type',
        ),
    ]
