# Generated by Django 4.2 on 2023-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_w_city_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
