# Generated by Django 4.2 on 2023-05-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('weather', '0006_city_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'user')},
        ),
    ]
