# Generated by Django 4.2 on 2023-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
