# Generated by Django 4.2 on 2023-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
